import logging

from viur.core.bones import *
from viur.core.skeleton import RelSkel, Skeleton


class StringRelSkel(RelSkel):
	lat = stringBone(
		descr=u"Latitude",
		indexed=True,
		searchable=True,
		required=True
	)

	lng = stringBone(
		descr=u"Longitude",
		indexed=True,
		searchable=True,
		required=True
	)


class allbonesSkel(Skeleton):
	# baseBone_0 = baseBone(descr="baseBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# baseBone_1 = baseBone(descr="baseBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# baseBone_2 = baseBone(descr="baseBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# baseBone_3 = baseBone(descr="baseBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# baseBone_4 = baseBone(descr="baseBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# baseBone_5 = baseBone(descr="baseBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# baseBone_6 = baseBone(descr="baseBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# baseBone_7 = baseBone(descr="baseBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# baseBone_8 = baseBone(descr="baseBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# baseBone_9 = baseBone(descr="baseBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# baseBone_10 = baseBone(descr="baseBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# baseBone_11 = baseBone(descr="baseBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# baseBone_12 = baseBone(descr="baseBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# baseBone_13 = baseBone(descr="baseBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# baseBone_14 = baseBone(descr="baseBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# baseBone_15 = baseBone(descr="baseBone_15", required=True, readOnly=True, visible=True, multiple=True)
	booleanBone_0 = booleanBone(descr="booleanBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# booleanBone_1 = booleanBone(descr="booleanBone_1", required=True, readOnly=False, visible=False, multiple=False)
	booleanBone_2 = booleanBone(descr="booleanBone_2", required=False, readOnly=True, visible=False, multiple=False)
	booleanBone_3 = booleanBone(descr="booleanBone_3", required=False, readOnly=False, visible=True, multiple=False)
	booleanBone_4 = booleanBone(descr="booleanBone_4", required=True, readOnly=True, visible=False, multiple=False)
	booleanBone_5 = booleanBone(descr="booleanBone_5", required=True, readOnly=False, visible=True, multiple=False)
	booleanBone_6 = booleanBone(descr="booleanBone_6", required=False, readOnly=True, visible=True, multiple=False)
	booleanBone_7 = booleanBone(descr="booleanBone_7", required=True, readOnly=True, visible=True, multiple=False)
	booleanBone_8 = booleanBone(descr="booleanBone_8", required=False, readOnly=False, visible=False, multiple=True)
	booleanBone_9 = booleanBone(descr="booleanBone_9", required=True, readOnly=False, visible=False, multiple=True)
	booleanBone_10 = booleanBone(descr="booleanBone_10", required=False, readOnly=True, visible=False, multiple=True)
	booleanBone_11 = booleanBone(descr="booleanBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# booleanBone_12 = booleanBone(descr="booleanBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# booleanBone_13 = booleanBone(descr="booleanBone_13", required=True, readOnly=False, visible=True, multiple=True)
	booleanBone_14 = booleanBone(descr="booleanBone_14", required=False, readOnly=True, visible=True, multiple=True)
	booleanBone_15 = booleanBone(descr="booleanBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# captchaBone_0 = captchaBone(descr="captchaBone_0", required=False, readOnly=False, visible=False, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_1 = captchaBone(descr="captchaBone_1", required=True, readOnly=False, visible=False, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_2 = captchaBone(descr="captchaBone_2", required=False, readOnly=True, visible=False, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_3 = captchaBone(descr="captchaBone_3", required=False, readOnly=False, visible=True, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_4 = captchaBone(descr="captchaBone_4", required=True, readOnly=True, visible=False, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_5 = captchaBone(descr="captchaBone_5", required=True, readOnly=False, visible=True, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_6 = captchaBone(descr="captchaBone_6", required=False, readOnly=True, visible=True, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_7 = captchaBone(descr="captchaBone_7", required=True, readOnly=True, visible=True, multiple=False, privateKey="foo", publicKey="bar")
	# captchaBone_8 = captchaBone(descr="captchaBone_8", required=False, readOnly=False, visible=False, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_9 = captchaBone(descr="captchaBone_9", required=True, readOnly=False, visible=False, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_10 = captchaBone(descr="captchaBone_10", required=False, readOnly=True, visible=False, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_11 = captchaBone(descr="captchaBone_11", required=False, readOnly=False, visible=True, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_12 = captchaBone(descr="captchaBone_12", required=True, readOnly=True, visible=False, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_13 = captchaBone(descr="captchaBone_13", required=True, readOnly=False, visible=True, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_14 = captchaBone(descr="captchaBone_14", required=False, readOnly=True, visible=True, multiple=True, privateKey="foo", publicKey="bar")
	# captchaBone_15 = captchaBone(descr="captchaBone_15", required=True, readOnly=True, visible=True, multiple=True, privateKey="foo", publicKey="bar")
	# colorBone_0 = colorBone(descr="colorBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# colorBone_1 = colorBone(descr="colorBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# colorBone_2 = colorBone(descr="colorBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# colorBone_3 = colorBone(descr="colorBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# colorBone_4 = colorBone(descr="colorBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# colorBone_5 = colorBone(descr="colorBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# colorBone_6 = colorBone(descr="colorBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# colorBone_7 = colorBone(descr="colorBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# colorBone_8 = colorBone(descr="colorBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# colorBone_9 = colorBone(descr="colorBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# colorBone_10 = colorBone(descr="colorBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# colorBone_11 = colorBone(descr="colorBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# colorBone_12 = colorBone(descr="colorBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# colorBone_13 = colorBone(descr="colorBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# colorBone_14 = colorBone(descr="colorBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# colorBone_15 = colorBone(descr="colorBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# credentialBone_0 = credentialBone(descr="credentialBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# credentialBone_1 = credentialBone(descr="credentialBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# credentialBone_2 = credentialBone(descr="credentialBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# credentialBone_3 = credentialBone(descr="credentialBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# credentialBone_4 = credentialBone(descr="credentialBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# credentialBone_5 = credentialBone(descr="credentialBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# credentialBone_6 = credentialBone(descr="credentialBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# credentialBone_7 = credentialBone(descr="credentialBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# # credentialBone_8 = credentialBone(descr="credentialBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# # credentialBone_9 = credentialBone(descr="credentialBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# # credentialBone_10 = credentialBone(descr="credentialBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# # credentialBone_11 = credentialBone(descr="credentialBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# # credentialBone_12 = credentialBone(descr="credentialBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# # credentialBone_13 = credentialBone(descr="credentialBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# # credentialBone_14 = credentialBone(descr="credentialBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# # credentialBone_15 = credentialBone(descr="credentialBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# dateBone_0 = dateBone(descr="dateBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# dateBone_1 = dateBone(descr="dateBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# dateBone_2 = dateBone(descr="dateBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# dateBone_3 = dateBone(descr="dateBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# dateBone_4 = dateBone(descr="dateBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# dateBone_5 = dateBone(descr="dateBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# dateBone_6 = dateBone(descr="dateBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# dateBone_7 = dateBone(descr="dateBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# dateBone_8 = dateBone(descr="dateBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# dateBone_9 = dateBone(descr="dateBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# dateBone_10 = dateBone(descr="dateBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# dateBone_11 = dateBone(descr="dateBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# dateBone_12 = dateBone(descr="dateBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# dateBone_13 = dateBone(descr="dateBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# dateBone_14 = dateBone(descr="dateBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# dateBone_15 = dateBone(descr="dateBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# emailBone_0 = emailBone(descr="emailBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# emailBone_1 = emailBone(descr="emailBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# emailBone_2 = emailBone(descr="emailBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# emailBone_3 = emailBone(descr="emailBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# emailBone_4 = emailBone(descr="emailBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# emailBone_5 = emailBone(descr="emailBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# emailBone_6 = emailBone(descr="emailBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# emailBone_7 = emailBone(descr="emailBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# emailBone_8 = emailBone(descr="emailBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# emailBone_9 = emailBone(descr="emailBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# emailBone_10 = emailBone(descr="emailBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# emailBone_11 = emailBone(descr="emailBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# emailBone_12 = emailBone(descr="emailBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# emailBone_13 = emailBone(descr="emailBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# emailBone_14 = emailBone(descr="emailBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# emailBone_15 = emailBone(descr="emailBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# fileBone_0 = fileBone(descr="fileBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# fileBone_1 = fileBone(descr="fileBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# fileBone_2 = fileBone(descr="fileBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# fileBone_3 = fileBone(descr="fileBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# fileBone_4 = fileBone(descr="fileBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# fileBone_5 = fileBone(descr="fileBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# fileBone_6 = fileBone(descr="fileBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# fileBone_7 = fileBone(descr="fileBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# fileBone_8 = fileBone(descr="fileBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# fileBone_9 = fileBone(descr="fileBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# fileBone_10 = fileBone(descr="fileBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# fileBone_11 = fileBone(descr="fileBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# fileBone_12 = fileBone(descr="fileBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# fileBone_13 = fileBone(descr="fileBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# fileBone_14 = fileBone(descr="fileBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# fileBone_15 = fileBone(descr="fileBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# keyBone_0 = keyBone(descr="keyBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# keyBone_1 = keyBone(descr="keyBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# keyBone_2 = keyBone(descr="keyBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# keyBone_3 = keyBone(descr="keyBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# keyBone_4 = keyBone(descr="keyBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# keyBone_5 = keyBone(descr="keyBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# keyBone_6 = keyBone(descr="keyBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# keyBone_7 = keyBone(descr="keyBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# keyBone_8 = keyBone(descr="keyBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# keyBone_9 = keyBone(descr="keyBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# keyBone_10 = keyBone(descr="keyBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# keyBone_11 = keyBone(descr="keyBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# keyBone_12 = keyBone(descr="keyBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# keyBone_13 = keyBone(descr="keyBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# keyBone_14 = keyBone(descr="keyBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# keyBone_15 = keyBone(descr="keyBone_15", required=True, readOnly=True, visible=True, multiple=True)
	numericBone_0 = numericBone(descr="numericBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# numericBone_1 = numericBone(descr="numericBone_1", required=True, readOnly=False, visible=False, multiple=False)
	numericBone_2 = numericBone(descr="numericBone_2", required=False, readOnly=True, visible=False, multiple=False)
	numericBone_3 = numericBone(descr="numericBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# numericBone_4 = numericBone(descr="numericBone_4", required=True, readOnly=True, visible=False, multiple=False)
	numericBone_5 = numericBone(descr="numericBone_5", required=True, readOnly=False, visible=True, multiple=False)
	numericBone_6 = numericBone(descr="numericBone_6", required=False, readOnly=True, visible=True, multiple=False)
	numericBone_7 = numericBone(descr="numericBone_7", required=True, readOnly=True, visible=True, multiple=False)
	numericBone_8 = numericBone(descr="numericBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# numericBone_9 = numericBone(descr="numericBone_9", required=True, readOnly=False, visible=False, multiple=True)
	numericBone_10 = numericBone(descr="numericBone_10", required=False, readOnly=True, visible=False, multiple=True)
	numericBone_11 = numericBone(descr="numericBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# numericBone_12 = numericBone(descr="numericBone_12", required=True, readOnly=True, visible=False, multiple=True)
	numericBone_13 = numericBone(descr="numericBone_13", required=True, readOnly=False, visible=True, multiple=True)
	numericBone_14 = numericBone(descr="numericBone_14", required=False, readOnly=True, visible=True, multiple=True)
	numericBone_15 = numericBone(descr="numericBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# passwordBone_0 = passwordBone(descr="passwordBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# passwordBone_1 = passwordBone(descr="passwordBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# passwordBone_2 = passwordBone(descr="passwordBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# passwordBone_3 = passwordBone(descr="passwordBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# passwordBone_4 = passwordBone(descr="passwordBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# passwordBone_5 = passwordBone(descr="passwordBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# passwordBone_6 = passwordBone(descr="passwordBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# passwordBone_7 = passwordBone(descr="passwordBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# passwordBone_8 = passwordBone(descr="passwordBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# passwordBone_9 = passwordBone(descr="passwordBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# passwordBone_10 = passwordBone(descr="passwordBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# passwordBone_11 = passwordBone(descr="passwordBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# passwordBone_12 = passwordBone(descr="passwordBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# passwordBone_13 = passwordBone(descr="passwordBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# passwordBone_14 = passwordBone(descr="passwordBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# passwordBone_15 = passwordBone(descr="passwordBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# # randomSliceBone_0 = randomSliceBone(descr="randomSliceBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# # randomSliceBone_1 = randomSliceBone(descr="randomSliceBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# randomSliceBone_2 = randomSliceBone(descr="randomSliceBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# # randomSliceBone_3 = randomSliceBone(descr="randomSliceBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# randomSliceBone_4 = randomSliceBone(descr="randomSliceBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# # randomSliceBone_5 = randomSliceBone(descr="randomSliceBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# # randomSliceBone_6 = randomSliceBone(descr="randomSliceBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# # randomSliceBone_7 = randomSliceBone(descr="randomSliceBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# # randomSliceBone_8 = randomSliceBone(descr="randomSliceBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# # randomSliceBone_9 = randomSliceBone(descr="randomSliceBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# randomSliceBone_10 = randomSliceBone(descr="randomSliceBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# # randomSliceBone_11 = randomSliceBone(descr="randomSliceBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# randomSliceBone_12 = randomSliceBone(descr="randomSliceBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# # randomSliceBone_13 = randomSliceBone(descr="randomSliceBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# # randomSliceBone_14 = randomSliceBone(descr="randomSliceBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# # randomSliceBone_15 = randomSliceBone(descr="randomSliceBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# # recordBone_0 = recordBone(descr="recordBone_0", required=False, readOnly=False, visible=False, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_1 = recordBone(descr="recordBone_1", required=True, readOnly=False, visible=False, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_2 = recordBone(descr="recordBone_2", required=False, readOnly=True, visible=False, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_3 = recordBone(descr="recordBone_3", required=False, readOnly=False, visible=True, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_4 = recordBone(descr="recordBone_4", required=True, readOnly=True, visible=False, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_5 = recordBone(descr="recordBone_5", required=True, readOnly=False, visible=True, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_6 = recordBone(descr="recordBone_6", required=False, readOnly=True, visible=True, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	# # recordBone_7 = recordBone(descr="recordBone_7", required=True, readOnly=True, visible=True, multiple=False, using=StringRelSkel, format="$(lat) - $(lng)")
	recordBone_8 = recordBone(descr="recordBone_8", required=False, readOnly=False, visible=False, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	# recordBone_9 = recordBone(descr="recordBone_9", required=True, readOnly=False, visible=False, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	recordBone_10 = recordBone(descr="recordBone_10", required=False, readOnly=True, visible=False, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	recordBone_11 = recordBone(descr="recordBone_11", required=False, readOnly=False, visible=True, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	# recordBone_12 = recordBone(descr="recordBone_12", required=True, readOnly=True, visible=False, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	recordBone_13 = recordBone(descr="recordBone_13", required=True, readOnly=False, visible=True, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	recordBone_14 = recordBone(descr="recordBone_14", required=False, readOnly=True, visible=True, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	recordBone_15 = recordBone(descr="recordBone_15", required=True, readOnly=True, visible=True, multiple=True, using=StringRelSkel, format="$(lat) - $(lng)")
	relationalBone_0 = relationalBone(descr="relationalBone_0", required=False, readOnly=False, visible=False, multiple=False, module="feedentry", kind="feedentry")
	# relationalBone_1 = relationalBone(descr="relationalBone_1", required=True, readOnly=False, visible=False, multiple=False, module="feedentry", kind="feedentry")
	relationalBone_2 = relationalBone(descr="relationalBone_2", required=False, readOnly=True, visible=False, multiple=False, module="feedentry", kind="feedentry")
	relationalBone_3 = relationalBone(descr="relationalBone_3", required=False, readOnly=False, visible=True, multiple=False, module="feedentry", kind="feedentry")
	# relationalBone_4 = relationalBone(descr="relationalBone_4", required=True, readOnly=True, visible=False, multiple=False, module="feedentry", kind="feedentry")
	relationalBone_5 = relationalBone(descr="relationalBone_5", required=True, readOnly=False, visible=True, multiple=False, module="feedentry", kind="feedentry")
	relationalBone_6 = relationalBone(descr="relationalBone_6", required=False, readOnly=True, visible=True, multiple=False, module="feedentry", kind="feedentry")
	relationalBone_7 = relationalBone(descr="relationalBone_7", required=True, readOnly=True, visible=True, multiple=False, module="feedentry", kind="feedentry")
	relationalBone_8 = relationalBone(descr="relationalBone_8", required=False, readOnly=False, visible=False, multiple=True, module="feedentry", kind="feedentry")
	# relationalBone_9 = relationalBone(descr="relationalBone_9", required=True, readOnly=False, visible=False, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_10 = relationalBone(descr="relationalBone_10", required=False, readOnly=True, visible=False, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_11 = relationalBone(descr="relationalBone_11", required=False, readOnly=False, visible=True, multiple=True, module="feedentry", kind="feedentry")
	# relationalBone_12 = relationalBone(descr="relationalBone_12", required=True, readOnly=True, visible=False, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_13 = relationalBone(descr="relationalBone_13", required=True, readOnly=False, visible=True, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_14 = relationalBone(descr="relationalBone_14", required=False, readOnly=True, visible=True, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_15 = relationalBone(descr="relationalBone_15", required=True, readOnly=True, visible=True, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_16 = relationalBone(descr="relationalBone_16", required=True, readOnly=True, visible=True, multiple=True, module="feedentry", kind="feedentry")
	relationalBone_17 = relationalBone(descr="relationalBone_17", required=True, readOnly=False, visible=True, multiple=True, module="feedentry", kind="feedentry", using=StringRelSkel)
	selectBone_0 = selectBone(descr="selectBone_0", required=False, readOnly=False, visible=False, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	# selectBone_1 = selectBone(descr="selectBone_1", required=True, readOnly=False, visible=False, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_2 = selectBone(descr="selectBone_2", required=False, readOnly=True, visible=False, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_3 = selectBone(descr="selectBone_3", required=False, readOnly=False, visible=True, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	# selectBone_4 = selectBone(descr="selectBone_4", required=True, readOnly=True, visible=False, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_5 = selectBone(descr="selectBone_5", required=True, readOnly=False, visible=True, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_6 = selectBone(descr="selectBone_6", required=False, readOnly=True, visible=True, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_7 = selectBone(descr="selectBone_7", required=True, readOnly=True, visible=True, multiple=False, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_8 = selectBone(descr="selectBone_8", required=False, readOnly=False, visible=False, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	# selectBone_9 = selectBone(descr="selectBone_9", required=True, readOnly=False, visible=False, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_10 = selectBone(descr="selectBone_10", required=False, readOnly=True, visible=False, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_11 = selectBone(descr="selectBone_11", required=False, readOnly=False, visible=True, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	# selectBone_12 = selectBone(descr="selectBone_12", required=True, readOnly=True, visible=False, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_13 = selectBone(descr="selectBone_13", required=True, readOnly=False, visible=True, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_14 = selectBone(descr="selectBone_14", required=False, readOnly=True, visible=True, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	selectBone_15 = selectBone(descr="selectBone_15", required=True, readOnly=True, visible=True, multiple=True, values={'true': '"Option A"', 'false': '"Option B"'})
	# selectCountryBone_0 = selectCountryBone(descr="selectCountryBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# selectCountryBone_1 = selectCountryBone(descr="selectCountryBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# selectCountryBone_2 = selectCountryBone(descr="selectCountryBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# selectCountryBone_3 = selectCountryBone(descr="selectCountryBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# selectCountryBone_4 = selectCountryBone(descr="selectCountryBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# selectCountryBone_5 = selectCountryBone(descr="selectCountryBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# selectCountryBone_6 = selectCountryBone(descr="selectCountryBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# selectCountryBone_7 = selectCountryBone(descr="selectCountryBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# selectCountryBone_8 = selectCountryBone(descr="selectCountryBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# selectCountryBone_9 = selectCountryBone(descr="selectCountryBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# selectCountryBone_10 = selectCountryBone(descr="selectCountryBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# selectCountryBone_11 = selectCountryBone(descr="selectCountryBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# selectCountryBone_12 = selectCountryBone(descr="selectCountryBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# selectCountryBone_13 = selectCountryBone(descr="selectCountryBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# selectCountryBone_14 = selectCountryBone(descr="selectCountryBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# selectCountryBone_15 = selectCountryBone(descr="selectCountryBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# spatialBone_0 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# spatialBone_1 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# spatialBone_2 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# spatialBone_3 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# spatialBone_4 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# spatialBone_5 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# spatialBone_6 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# spatialBone_7 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# spatialBone_8 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# spatialBone_9 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# spatialBone_10 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# spatialBone_11 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# spatialBone_12 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# spatialBone_13 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# spatialBone_14 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# spatialBone_15 = spatialBone((50, 57), (7, 0), (10, 10), descr="spatialBone_15", required=True, readOnly=True, visible=True, multiple=True)
	stringBone_0 = stringBone(descr="stringBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# stringBone_1 = stringBone(descr="stringBone_1", required=True, readOnly=False, visible=False, multiple=False)
	stringBone_2 = stringBone(descr="stringBone_2", required=False, readOnly=True, visible=False, multiple=False)
	stringBone_3 = stringBone(descr="stringBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# stringBone_4 = stringBone(descr="stringBone_4", required=True, readOnly=True, visible=False, multiple=False)
	stringBone_5 = stringBone(descr="stringBone_5", required=True, readOnly=False, visible=True, multiple=False)
	stringBone_6 = stringBone(descr="stringBone_6", required=False, readOnly=True, visible=True, multiple=False)
	stringBone_7 = stringBone(descr="stringBone_7", required=True, readOnly=True, visible=True, multiple=False)
	stringBone_8 = stringBone(descr="stringBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# stringBone_9 = stringBone(descr="stringBone_9", required=True, readOnly=False, visible=False, multiple=True)
	stringBone_10 = stringBone(descr="stringBone_10", required=False, readOnly=True, visible=False, multiple=True)
	stringBone_11 = stringBone(descr="stringBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# stringBone_12 = stringBone(descr="stringBone_12", required=True, readOnly=True, visible=False, multiple=True)
	stringBone_13 = stringBone(descr="stringBone_13", required=True, readOnly=False, visible=True, multiple=True)
	stringBone_14 = stringBone(descr="stringBone_14", required=False, readOnly=True, visible=True, multiple=True)
	stringBone_15 = stringBone(descr="stringBone_15", required=True, readOnly=True, visible=True, multiple=True)
	# treeLeafBone_0 = treeLeafBone(descr="treeLeafBone_0", required=False, readOnly=False, visible=False, multiple=False, module="file", kind="file")
	# treeLeafBone_1 = treeLeafBone(descr="treeLeafBone_1", required=True, readOnly=False, visible=False, multiple=False, module="file", kind="file")
	# treeLeafBone_2 = treeLeafBone(descr="treeLeafBone_2", required=False, readOnly=True, visible=False, multiple=False, module="file", kind="file")
	# treeLeafBone_3 = treeLeafBone(descr="treeLeafBone_3", required=False, readOnly=False, visible=True, multiple=False, module="file", kind="file")
	# treeLeafBone_4 = treeLeafBone(descr="treeLeafBone_4", required=True, readOnly=True, visible=False, multiple=False, module="file", kind="file")
	# treeLeafBone_5 = treeLeafBone(descr="treeLeafBone_5", required=True, readOnly=False, visible=True, multiple=False, module="file", kind="file")
	# treeLeafBone_6 = treeLeafBone(descr="treeLeafBone_6", required=False, readOnly=True, visible=True, multiple=False, module="file", kind="file")
	# treeLeafBone_7 = treeLeafBone(descr="treeLeafBone_7", required=True, readOnly=True, visible=True, multiple=False, module="file", kind="file")
	# treeLeafBone_8 = treeLeafBone(descr="treeLeafBone_8", required=False, readOnly=False, visible=False, multiple=True, module="file", kind="file")
	# treeLeafBone_9 = treeLeafBone(descr="treeLeafBone_9", required=True, readOnly=False, visible=False, multiple=True, module="file", kind="file")
	# treeLeafBone_10 = treeLeafBone(descr="treeLeafBone_10", required=False, readOnly=True, visible=False, multiple=True, module="file", kind="file")
	# treeLeafBone_11 = treeLeafBone(descr="treeLeafBone_11", required=False, readOnly=False, visible=True, multiple=True, module="file", kind="file")
	# treeLeafBone_12 = treeLeafBone(descr="treeLeafBone_12", required=True, readOnly=True, visible=False, multiple=True, module="file", kind="file")
	# treeLeafBone_13 = treeLeafBone(descr="treeLeafBone_13", required=True, readOnly=False, visible=True, multiple=True, module="file", kind="file")
	# treeLeafBone_14 = treeLeafBone(descr="treeLeafBone_14", required=False, readOnly=True, visible=True, multiple=True, module="file", kind="file")
	# treeLeafBone_15 = treeLeafBone(descr="treeLeafBone_15", required=True, readOnly=True, visible=True, multiple=True, module="file", kind="file")
	# treeNodeBone_0 = treeNodeBone(descr="treeNodeBone_0", required=False, readOnly=False, visible=False, multiple=False, module="file", kind="file")
	# treeNodeBone_1 = treeNodeBone(descr="treeNodeBone_1", required=True, readOnly=False, visible=False, multiple=False, module="file", kind="file")
	# treeNodeBone_2 = treeNodeBone(descr="treeNodeBone_2", required=False, readOnly=True, visible=False, multiple=False, module="file", kind="file")
	# treeNodeBone_3 = treeNodeBone(descr="treeNodeBone_3", required=False, readOnly=False, visible=True, multiple=False, module="file", kind="file")
	# treeNodeBone_4 = treeNodeBone(descr="treeNodeBone_4", required=True, readOnly=True, visible=False, multiple=False, module="file", kind="file")
	# treeNodeBone_5 = treeNodeBone(descr="treeNodeBone_5", required=True, readOnly=False, visible=True, multiple=False, module="file", kind="file")
	# treeNodeBone_6 = treeNodeBone(descr="treeNodeBone_6", required=False, readOnly=True, visible=True, multiple=False, module="file", kind="file")
	# treeNodeBone_7 = treeNodeBone(descr="treeNodeBone_7", required=True, readOnly=True, visible=True, multiple=False, module="file", kind="file")
	# treeNodeBone_8 = treeNodeBone(descr="treeNodeBone_8", required=False, readOnly=False, visible=False, multiple=True, module="file", kind="file")
	# treeNodeBone_9 = treeNodeBone(descr="treeNodeBone_9", required=True, readOnly=False, visible=False, multiple=True, module="file", kind="file")
	# treeNodeBone_10 = treeNodeBone(descr="treeNodeBone_10", required=False, readOnly=True, visible=False, multiple=True, module="file", kind="file")
	# treeNodeBone_11 = treeNodeBone(descr="treeNodeBone_11", required=False, readOnly=False, visible=True, multiple=True, module="file", kind="file")
	# treeNodeBone_12 = treeNodeBone(descr="treeNodeBone_12", required=True, readOnly=True, visible=False, multiple=True, module="file", kind="file")
	# treeNodeBone_13 = treeNodeBone(descr="treeNodeBone_13", required=True, readOnly=False, visible=True, multiple=True, module="file", kind="file")
	# treeNodeBone_14 = treeNodeBone(descr="treeNodeBone_14", required=False, readOnly=True, visible=True, multiple=True, module="file", kind="file")
	# treeNodeBone_15 = treeNodeBone(descr="treeNodeBone_15", required=True, readOnly=True, visible=True, multiple=True, module="file", kind="file")
	# userBone_0 = userBone(descr="userBone_0", required=False, readOnly=False, visible=False, multiple=False)
	# userBone_1 = userBone(descr="userBone_1", required=True, readOnly=False, visible=False, multiple=False)
	# userBone_2 = userBone(descr="userBone_2", required=False, readOnly=True, visible=False, multiple=False)
	# userBone_3 = userBone(descr="userBone_3", required=False, readOnly=False, visible=True, multiple=False)
	# userBone_4 = userBone(descr="userBone_4", required=True, readOnly=True, visible=False, multiple=False)
	# userBone_5 = userBone(descr="userBone_5", required=True, readOnly=False, visible=True, multiple=False)
	# userBone_6 = userBone(descr="userBone_6", required=False, readOnly=True, visible=True, multiple=False)
	# userBone_7 = userBone(descr="userBone_7", required=True, readOnly=True, visible=True, multiple=False)
	# userBone_8 = userBone(descr="userBone_8", required=False, readOnly=False, visible=False, multiple=True)
	# userBone_9 = userBone(descr="userBone_9", required=True, readOnly=False, visible=False, multiple=True)
	# userBone_10 = userBone(descr="userBone_10", required=False, readOnly=True, visible=False, multiple=True)
	# userBone_11 = userBone(descr="userBone_11", required=False, readOnly=False, visible=True, multiple=True)
	# userBone_12 = userBone(descr="userBone_12", required=True, readOnly=True, visible=False, multiple=True)
	# userBone_13 = userBone(descr="userBone_13", required=True, readOnly=False, visible=True, multiple=True)
	# userBone_14 = userBone(descr="userBone_14", required=False, readOnly=True, visible=True, multiple=True)
	# userBone_15 = userBone(descr="userBone_15", required=True, readOnly=True, visible=True, multiple=True)
